### ISSUE TITLE
some tests not running

### ISSUE THREAD

**Issue by michaelhitzker** [htl-perg-2019-20-5bhif/cash-desk-exercise-michaelhitzker#1]
Dear Mr. Stropek!

I have implemented the solution, but some tests did not run. I have no idea why. However, the tests that ran were successful. I had a look at your solution and think that the tests which did not run should pass. 

![tests_cash_desk](https://user-images.githubusercontent.com/33837887/68545497-fada2200-03cd-11ea-92a7-0d11d2ed2c65.JPG)

I sometimes had a look at your solution during the implementation, as I sometimes did not know how to continue. I hope that is ok.

Kind regards
Michael Hitzker

**Comment by rstropek** [comment]
Hi @michaelhitzker!

It is absolutely no problem if you take a look at my implementation. That's why I created it.

Regarding your problem: You created an endless recursion in `Membership` ([here](https://github.com/htl-perg-2019-20-5bhif/cash-desk-exercise-michaelhitzker/blob/4acc58f7522bd7501a16cbcdb6ed36ab3cbd8093/CashDesk/Membership.cs#L18)). You access `End` inside the getter for `End` -> recursion.

This is how you can fix the problem:

```csharp
private DateTime EndValue;

public DateTime End
{
    get { return EndValue; }
    set
    {
        if (value <= Begin)
        {
            throw new ArgumentException("End must be later than begin");
        }
        EndValue = value;
    }
}
```

If you do that, all tests run - but not yet successful. I hope that helps completing the exercise.

Greetings,
Rainer Stropek.

**Comment by michaelhitzker** [comment]
Dear Mr. Stropek!

Thanks for the help! I fixed the failing tests and now all tests pass.
